### ISSUE TITLE
draw method does not match documentation and is untested

### ISSUE THREAD

**Issue by shawnlaffan** [shawnlaffan/perl-statistics-sampler-multinomial#3]
The draw method for Statistics::Sampler::Multinomial returns an array instead of the class number (as documented).  

It is also untested.  

Statistics::Sampler::Multinomial::Alias is not affected

**Comment by shawnlaffan** [comment]
code updated in 66b5aa7160c7b112dde826186a16401767520015

**Comment by y722** [comment]
> ترجع طريقة الرسم لـ Statistics :: Sampler :: Multinomial مصفوفة بدلاً من رقم الفئة (كما هو موثق).
> 
> كما أنه لم يتم اختباره.
> 
> الإحصائيات :: Sampler :: Multinomial :: الاسم المستعار لا يتأثر
